export { satelliteAccess, satelliteAccessRules } from "./access";
export {
  satelliteContract,
  SatelliteApi,
  type SatelliteContract,
} from "./rpc-contract";
export {
  SatelliteStatusSchema,
  SatelliteSchema,
  SatelliteWithStatusSchema,
  CreateSatelliteSchema,
  type SatelliteStatus,
  type Satellite,
  type SatelliteWithStatus,
  type CreateSatellite,
} from "./schemas";
export {
  SatelliteAssignmentSchema,
  SatelliteEnvironmentSchema,
  SatelliteToCoreMessageSchema,
  CoreToSatelliteMessageSchema,
  type SatelliteAssignment,
  type SatelliteEnvironment,
  type SatelliteToCoreMessage,
  type CoreToSatelliteMessage,
  type AuthenticateMessage,
  type HeartbeatMessage,
  type ResultMessage,
  type StrategyErrorMessage,
  type AuthenticatedMessage,
  type AuthFailedMessage,
  type ConfigUpdatedMessage,
  type ShutdownMessage,
  type ScriptPackageSyncStateMessage,
  type RefreshScriptPackagesMessage,
  type ScriptPackageManifestMessage,
  type ScriptPackageBlobMessage,
  type RequestScriptPackageManifestMessage,
  type RequestScriptPackageBlobMessage,
  type RequestRunSecretsMessage,
  type RunSecretsMessage,
  type RequestConfigSecretsMessage,
  type ConfigSecretsMessage,
  type TelemetryBatchMessage,
  type CapabilityStatusMessage,
  type CapabilitySecretRequestMessage,
  type TelemetryAckMessage,
  type CapabilityConfigMessage,
  type CapabilitySecretResponseMessage,
} from "./protocol";
export {
  SATELLITE_STATUS_CHANGED,
  SATELLITE_CONFIG_CHANGED,
} from "./signals";
export {
  HEARTBEAT_INTERVAL_MS,
  OFFLINE_THRESHOLD_MS,
  RESULT_BUFFER_CAPACITY,
  RECONNECT_BASE_MS,
  RECONNECT_MAX_MS,
  TELEMETRY_MAX_INFLIGHT,
  TELEMETRY_BATCH_MAX_ITEMS,
  TELEMETRY_BATCH_MAX_BYTES,
  TELEMETRY_DEDUPE_WINDOW,
  TELEMETRY_BUDGET_BYTES_PER_MIN,
  TELEMETRY_ACK_TIMEOUT_MS,
  TELEMETRY_PUMP_INTERVAL_MS,
} from "./constants";
export * from "./plugin-metadata";
export { satelliteRoutes } from "./routes";
