name: "🐛 Bug Report"
description: Report a bug or unexpected behavior in Checkmate
title: "[Bug]: "
labels: ["bug", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for helping improve Checkmate! Please fill out this form completely.

        > ⚠️ **Important**: Bug reports without a reproduction example will not be reviewed.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to..., the application...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        **This field is required.** Provide detailed steps to reproduce the bug.
        Bug reports without clear reproduction steps will not be reviewed.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: reproduction-example
    attributes:
      label: Reproduction Example
      description: |
        **This field is required.** Provide a minimal reproduction example.
        This can be:
        - A link to a repository with a minimal reproduction
        - A code snippet that demonstrates the issue
        - A link to a deployed instance where the bug can be observed
        - Detailed configuration/environment setup to reproduce
      placeholder: |
        Example repository: https://github.com/...

        Or provide configuration:
        ```yaml
        # docker-compose.yml or relevant config
        ```

        Or code snippet:
        ```typescript
        // Code that triggers the bug
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: Instead, the application...
    validations:
      required: true

  - type: dropdown
    id: criticality
    attributes:
      label: Criticality
      description: |
        Select the appropriate criticality level for this bug:
        - **Critical**: System is completely unusable, data loss, or security vulnerability. Affects all users.
        - **High**: Major feature is broken with no workaround. Significantly impacts user workflow.
        - **Medium**: Feature is impaired but a workaround exists. Moderate impact on user experience.
        - **Low**: Minor issue, cosmetic bug, or edge case. Does not significantly affect functionality.
      options:
        - "critical"
        - "high"
        - "medium"
        - "low"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: |
        - Checkmate Version: [e.g., 1.2.0]
        - Deployment Method: [e.g., Docker, Bare Metal]
        - Browser (if frontend issue): [e.g., Chrome 120, Firefox 121]
        - Operating System: [e.g., Ubuntu 22.04, macOS 14]
        - Bun Version (if applicable): [e.g., 1.3.5]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include any relevant log output. This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing and able to contribute a fix for this bug?
      options:
        - "Yes, I can fix this bug and submit a PR"
        - "Yes, but I would need guidance on the fix"
        - "No, I am reporting this bug but cannot contribute a fix"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. Screenshots, screen recordings, etc.
    validations:
      required: false
