/**
 * The message protocol between the main thread and an ingest flush worker
 * (plan §5, Phase D). Every message is a structured-cloneable discriminated
 * union - no functions, no class instances beyond `Date` (which structured clone
 * supports) - so it survives `postMessage` in both directions. There is exactly
 * one union per direction; the `type` field discriminates.
 *
 * WHY these shapes (Option B, per the approved design):
 * - The main thread keeps HTTP auth, parse, normalize, rate limiting, the write
 *   buffer + 429 backpressure, ALL DB writes, signals and the fast-path hook. It
 *   ships a worker only the offloadable stage: a per-stream batch of ALREADY
 *   parsed+normalized {@link IngestedLine}s plus the resolved config, and gets
 *   back a {@link FlushPlan} it writes exactly as it does in-process.
 * - The worker owns the Drain trees for the streams that hash to it (classify +
 *   wildcardValues + user patterns + protected sets), severity patternOverrides,
 *   sampling and the per-minute fold. It holds NO DB connection: when it must
 *   hydrate a stream's tree it asks the main thread for the pattern rows
 *   ({@link WorkerHydrateRequest} -> {@link MainHydrateResponse}).
 * - Cross-worker state sync (user-pattern upsert/remove, healthcheck-referenced
 *   protected set) is proxied from the main thread into the OWNING worker so the
 *   tree the worker classifies against stays consistent with main-thread events.
 */

import type { IngestedLine, LogStreamConfig } from "@checkstack/logstream-common";
import type { DrainPatternRow } from "../../drain/engine";
import type { FlushPlan } from "../flush";

/** Correlates a request with its response across the channel. Monotonic per sender. */
export type RequestId = number;

// ---------------------------------------------------------------------------
// Main thread -> worker
// ---------------------------------------------------------------------------

/**
 * Classify + fold + sample a stream's buffered lines. `nowMs` is the flush's
 * SERVER time as epoch millis (rebuilt into a `Date` in the worker); the lines
 * carry their own clamped event/observed timestamps. Answered by exactly one
 * {@link WorkerFlushResult} or {@link WorkerFlushError} with the same `requestId`.
 */
export interface MainFlushRequest {
  type: "flush";
  requestId: RequestId;
  streamId: string;
  lines: IngestedLine[];
  config: LogStreamConfig;
  nowMs: number;
  flushIntervalMs: number;
}

/** Install/refresh a user-authored protected cluster on the owning worker's tree. */
export interface MainUpsertUserPattern {
  type: "upsert-user-pattern";
  streamId: string;
  template: string;
}

/** Drop a user-authored cluster from the owning worker's tree. */
export interface MainRemoveUserPattern {
  type: "remove-user-pattern";
  streamId: string;
  patternId: string;
}

/** Replace a stream's healthcheck-referenced protected id set on the owning worker. */
export interface MainSetProtectedPatterns {
  type: "set-protected-patterns";
  streamId: string;
  patternIds: readonly string[];
}

/** The pattern rows the worker asked for (answers a {@link WorkerHydrateRequest}). */
export interface MainHydrateResponse {
  type: "hydrate-response";
  requestId: RequestId;
  rows: DrainPatternRow[];
}

/**
 * The main thread could not fetch the requested rows. The worker proceeds
 * UNSEEDED for that stream (it re-mines and converges), exactly as the in-process
 * path swallows a hydration failure and classifies anyway.
 */
export interface MainHydrateError {
  type: "hydrate-error";
  requestId: RequestId;
  message: string;
}

/** Ask the worker to wind down; answered by {@link WorkerStopped}. */
export interface MainStop {
  type: "stop";
  requestId: RequestId;
}

export type MainToWorkerMessage =
  | MainFlushRequest
  | MainUpsertUserPattern
  | MainRemoveUserPattern
  | MainSetProtectedPatterns
  | MainHydrateResponse
  | MainHydrateError
  | MainStop;

// ---------------------------------------------------------------------------
// Worker -> main thread
// ---------------------------------------------------------------------------

/** Emitted once the worker module has booted and installed its message handler. */
export interface WorkerReady {
  type: "ready";
}

/** The computed plan for a {@link MainFlushRequest}, ready for the main thread to write. */
export interface WorkerFlushResult {
  type: "flush-result";
  requestId: RequestId;
  plan: FlushPlan;
}

/** Classification failed for a {@link MainFlushRequest}; the main thread drops the batch. */
export interface WorkerFlushError {
  type: "flush-error";
  requestId: RequestId;
  message: string;
}

/**
 * The worker needs a stream's persisted pattern rows to hydrate its tree. The
 * `requestId` is generated by the WORKER and echoed back in the matching
 * {@link MainHydrateResponse} / {@link MainHydrateError}.
 */
export interface WorkerHydrateRequest {
  type: "hydrate-request";
  requestId: RequestId;
  streamId: string;
}

/** Acknowledges a {@link MainStop}: the worker is drained and safe to terminate. */
export interface WorkerStopped {
  type: "stopped";
  requestId: RequestId;
}

export type WorkerToMainMessage =
  | WorkerReady
  | WorkerFlushResult
  | WorkerFlushError
  | WorkerHydrateRequest
  | WorkerStopped;
