#!/usr/bin/env bun
/**
 * Generates the build-time bundled documentation index for the AI assistant's
 * `ai.searchDocs` / `ai.getDoc` tools (plan §3.4). Walks the authored Starlight
 * markdown under `docs/src/content/docs/**` and emits a generated runtime
 * `DOCS_INDEX` constant — exactly mirroring how the SDK editor bundle ships
 * `SDK_EDITOR_BUNDLE_DTS` as a generated runtime string
 * (core/sdk/src/editor-bundle.ts).
 *
 * Why bundled and NOT runtime-fetched (RESOLVED, plan OQ-3): the docs the
 * assistant cites are versioned with the backend build — no network/egress
 * dependency, no version skew with GitHub Pages, works offline / air-gapped.
 *
 * Emits (committed):
 *   core/ai-backend/src/generated/docs-index.ts - the DOCS_INDEX constant + hash
 *
 * Modes:
 *   - default: write the generated file to disk.
 *   - --check: regenerate to an in-memory buffer and diff against the committed
 *     file; exit 1 on drift. Run in CI so a docs change without a regenerated
 *     index fails (mirrors `generate:sdk:check`).
 *
 * Idempotent: a fresh run on unchanged inputs produces byte-identical output
 * (entries sorted by slug; deterministic hash).
 */

import {
  createHash,
} from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const DOCS_ROOT = path.join(ROOT, "docs", "src", "content", "docs");
const OUTPUT_FILE = path.join(
  ROOT,
  "core",
  "ai-backend",
  "src",
  "generated",
  "docs-index.ts",
);

const CHECK_ONLY = process.argv.includes("--check");

/**
 * Per-page `content` size budget (plan OQ-11). Pages longer than this are
 * truncated; `getDoc` flags `truncated: true`. 24 KB keeps a `searchDocs` plus a
 * couple of `getDoc` calls comfortably within a single model turn's context.
 */
export const DOCS_CONTENT_MAX_BYTES = 24 * 1024;

const GENERATED_BANNER =
  "// AUTO-GENERATED by scripts/generate-docs-index.ts - DO NOT EDIT BY HAND.\n" +
  "// Run `bun run generate:docs-index` after changing any page under\n" +
  "// docs/src/content/docs/**.\n";

/** One indexed documentation page. Mirrors `DocsIndexEntry` in the emitted file. */
export interface DocsIndexEntry {
  /** Slug-based address, e.g. "user-guide/concepts/health-checks". */
  slug: string;
  /** From frontmatter `title:` (falls back to the first H1, else the slug). */
  title: string;
  /** From frontmatter `description:` (when present). */
  description?: string;
  /** All `##`/`###`/... heading texts, for ranking. */
  headings: string[];
  /** Full page body, frontmatter + MDX component imports stripped, byte-capped. */
  content: string;
  /** True when `content` was truncated to the size budget. */
  truncated: boolean;
}

/** A discovered source file. */
interface SourceFile {
  /** Absolute path. */
  abs: string;
  /** Path relative to DOCS_ROOT, POSIX-separated. */
  rel: string;
}

/** Recursively lists `.md`/`.mdx` files under a directory, sorted for determinism. */
export function listDocFiles(docsRoot: string): SourceFile[] {
  const out: SourceFile[] = [];
  const walk = (dir: string): void => {
    if (!existsSync(dir)) return;
    const entries = readdirSync(dir, { withFileTypes: true }).toSorted((a, b) =>
      a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
    );
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(abs);
      } else if (entry.isFile() && /\.(md|mdx)$/.test(entry.name)) {
        const rel = path.relative(docsRoot, abs).split(path.sep).join("/");
        out.push({ abs, rel });
      }
    }
  };
  walk(docsRoot);
  return out;
}

/**
 * Derives the Starlight slug from a file path relative to the docs root:
 * - drop the extension;
 * - `index.md(x)` maps to its directory slug;
 * - the docs-root `index.md(x)` maps to the empty slug "".
 * Matches Starlight's slug-based routing.
 */
export function deriveSlug(rel: string): string {
  const noExt = rel.replace(/\.(md|mdx)$/, "");
  if (noExt === "index") return "";
  if (noExt.endsWith("/index")) return noExt.slice(0, -"/index".length);
  return noExt;
}

interface ParsedFrontmatter {
  title?: string;
  description?: string;
  /** The body with the frontmatter block removed. */
  body: string;
}

/**
 * Parses the leading YAML frontmatter block (a `---` fenced block at the very
 * start of the file). Only `title` and `description` scalar keys are read; the
 * rest is ignored. A scalar may be quoted (single/double) or bare.
 */
export function parseFrontmatter(raw: string): ParsedFrontmatter {
  // Normalize CRLF so the parse + content hash are platform-independent.
  const normalized = raw.replaceAll('\r\n', "\n");
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(normalized);
  if (!match) return { body: normalized };

  const fm = match[1] ?? "";
  const body = normalized.slice(match[0].length);

  const readScalar = (key: string): string | undefined => {
    // Match `key: value` at the start of a frontmatter line (top-level only).
    const re = new RegExp(String.raw`^${key}:[ \t]*(.*)$`, "m");
    const m = re.exec(fm);
    if (!m) return undefined;
    let value = (m[1] ?? "").trim();
    if (value.length === 0) return undefined;
    // Strip a single matching pair of surrounding quotes.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
      // Unescape an escaped quote of the same kind inside a double-quoted value.
      value = value.replaceAll(/\\(["'])/g, "$1");
    }
    return value.length > 0 ? value : undefined;
  };

  return {
    title: readScalar("title"),
    description: readScalar("description"),
    body,
  };
}

/**
 * Strips MDX `import`/`export` statement lines and standalone JSX component
 * lines from a body so the indexed content is plain prose. Code fences are kept
 * verbatim (their text is still useful for matching), but JSX-only lines and
 * Starlight component tags are dropped.
 */
export function stripMdx(body: string): string {
  const lines = body.split("\n");
  const kept: string[] = [];
  let inFence = false;
  // When inside a multi-line JSX component tag (an open tag whose `>` is on a
  // later line, e.g. a `<LinkCard\n  title=...\n/>` block), drop lines until the
  // tag closes. Component PROPS are layout metadata, not prose.
  let inOpenTag = false;
  for (const line of lines) {
    const fence = /^\s*(```|~~~)/.test(line);
    if (fence) {
      inFence = !inFence;
      kept.push(line);
      continue;
    }
    if (inFence) {
      kept.push(line);
      continue;
    }
    const trimmed = line.trim();
    if (inOpenTag) {
      // Still consuming a multi-line component tag; it ends on the line bearing
      // the closing `>` (or `/>`).
      if (/\/?>\s*$/.test(trimmed)) inOpenTag = false;
      continue;
    }
    // Drop ESM import/export lines (MDX component imports).
    if (/^(import|export)\b/.test(trimmed)) continue;
    // Drop lines that are ONLY a JSX/Starlight component open/close/self-close
    // tag on a single line (e.g. `<CardGrid>`, `</CardGrid>`, `<LinkCard ... />`).
    if (/^<\/?[A-Z][\w.]*(\s[^>]*)?\/?>$/.test(trimmed)) continue;
    // A multi-line component open tag: `<LinkCard` with no closing `>` yet.
    if (/^<[A-Z][\w.]*\b[^>]*$/.test(trimmed) && !trimmed.includes(">")) {
      inOpenTag = true;
      continue;
    }
    kept.push(line);
  }
  // Collapse 3+ blank lines left by stripping into a single blank line.
  return kept.join("\n").replaceAll(/\n{3,}/g, "\n\n").trim();
}

/** Extracts ATX heading texts (`##`..`######`) from a (frontmatter-stripped) body. */
export function extractHeadings(body: string): string[] {
  const headings: string[] = [];
  let inFence = false;
  for (const line of body.split("\n")) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    const m = /^(#{2,6})\s+(.+?)\s*#*\s*$/.exec(line);
    if (m) headings.push((m[2] ?? "").trim());
  }
  return headings;
}

/** Extracts the first H1 (`# ...`) text, if any, from a body. */
function firstH1(body: string): string | undefined {
  for (const line of body.split("\n")) {
    const m = /^#\s+(.+?)\s*#*\s*$/.exec(line);
    if (m) return (m[1] ?? "").trim();
  }
  return undefined;
}

/**
 * Caps a string at a UTF-8 byte budget WITHOUT splitting a multi-byte codepoint.
 * Returns the (possibly unchanged) string and whether it was truncated.
 */
export function capBytes(
  text: string,
  maxBytes: number,
): { text: string; truncated: boolean } {
  const buf = Buffer.from(text, "utf8");
  if (buf.length <= maxBytes) return { text, truncated: false };
  // Trim back to a codepoint boundary: a UTF-8 continuation byte is 0b10xxxxxx.
  let end = maxBytes;
  while (end > 0 && (buf[end] ?? 0) >= 0x80 && (buf[end] ?? 0) < 0xC0) {
    end -= 1;
  }
  return { text: buf.subarray(0, end).toString("utf8"), truncated: true };
}

/** Builds one index entry from a source file's raw contents. */
export function buildEntry({
  rel,
  raw,
}: {
  rel: string;
  raw: string;
}): DocsIndexEntry {
  const slug = deriveSlug(rel);
  const { title: fmTitle, description, body } = parseFrontmatter(raw);
  const stripped = stripMdx(body);
  const headings = extractHeadings(body);
  const title = fmTitle ?? firstH1(body) ?? (slug === "" ? "index" : slug);
  const { text: content, truncated } = capBytes(stripped, DOCS_CONTENT_MAX_BYTES);
  return {
    slug,
    title,
    ...(description ? { description } : {}),
    headings,
    content,
    truncated,
  };
}

/** Builds the full, slug-sorted index from a docs root. Pure over its input. */
export function buildDocsIndex(
  docsRoot: string = DOCS_ROOT,
): DocsIndexEntry[] {
  return listDocFiles(docsRoot)
    .map(({ abs, rel }) => buildEntry({ rel, raw: readFileSync(abs, "utf8") }))
    .toSorted((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0));
}

/**
 * A content hash of the index, so a CI `--check` run can detect drift. Derived
 * from the normalized, serialized entries (not raw file bytes) so it is stable
 * across platforms and re-orderings.
 */
export function hashIndex(index: DocsIndexEntry[]): string {
  const hash = createHash("sha256");
  for (const entry of index) {
    hash.update(entry.slug);
    hash.update(" ");
    hash.update(entry.title);
    hash.update(" ");
    hash.update(entry.description ?? "");
    hash.update(" ");
    hash.update(entry.headings.join(" "));
    hash.update(" ");
    hash.update(entry.content);
    hash.update(" ");
    hash.update(entry.truncated ? "1" : "0");
    // A genuine record separator between entries so two adjacent fields can't
    // collide across an entry boundary (e.g. one entry's trailing field
    // concatenating with the next entry's leading slug).
    hash.update("\n--\n");
  }
  return hash.digest("hex");
}

/** Renders the generated `docs-index.ts` module text. Deterministic. */
export function renderDocsIndexModule(index: DocsIndexEntry[]): string {
  const hash = hashIndex(index);
  return (
    GENERATED_BANNER +
    "\n" +
    "/** One indexed documentation page (build-time bundled, plan §3.4). */\n" +
    "export interface DocsIndexEntry {\n" +
    "  /** Slug-based address, e.g. \"user-guide/concepts/health-checks\". */\n" +
    "  slug: string;\n" +
    "  /** From frontmatter `title:`. */\n" +
    "  title: string;\n" +
    "  /** From frontmatter `description:` (when present). */\n" +
    "  description?: string;\n" +
    "  /** All `##`/`###`/... heading texts, for ranking. */\n" +
    "  headings: string[];\n" +
    "  /** Full page body, frontmatter + MDX component imports stripped. */\n" +
    "  content: string;\n" +
    "  /** True when `content` was truncated to the build-time size budget. */\n" +
    "  truncated: boolean;\n" +
    "}\n\n" +
    "/** Every authored docs page, sorted by slug. Bundled into the backend. */\n" +
    "export const DOCS_INDEX: readonly DocsIndexEntry[] = " +
    JSON.stringify(index, undefined, 2) +
    ";\n\n" +
    "/** A content hash of the source tree, so a CI check can detect drift. */\n" +
    "export const DOCS_INDEX_HASH = " +
    JSON.stringify(hash) +
    ";\n"
  );
}

/** Builds the single emitted file (absolute path + content). */
export function buildEmitFile({
  docsRoot = DOCS_ROOT,
  outputFile = OUTPUT_FILE,
}: { docsRoot?: string; outputFile?: string } = {}): {
  file: string;
  content: string;
} {
  const index = buildDocsIndex(docsRoot);
  return { file: outputFile, content: renderDocsIndexModule(index) };
}

function main(): void {
  // Guard: a misconfigured CWD would silently emit an empty index.
  if (!existsSync(DOCS_ROOT) || !statSync(DOCS_ROOT).isDirectory()) {
    console.error(`❌ Docs root not found: ${DOCS_ROOT}`);
    process.exit(1);
  }

  const { file, content } = buildEmitFile();

  if (CHECK_ONLY) {
    const prev = existsSync(file) ? readFileSync(file, "utf8") : undefined;
    if (prev !== content) {
      console.error(
        "❌ The bundled docs index is out of sync with docs/src/content/docs/**:",
      );
      console.error(`   - ${path.relative(ROOT, file)}`);
      console.error(
        "\nRun `bun run generate:docs-index` and commit the change. A docs page " +
          "change MUST regenerate the bundled index so the assistant can cite it.",
      );
      process.exit(1);
    }
    console.log("✓ Bundled docs index is up to date.");
    return;
  }

  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content, "utf8");
  console.log(`✓ Generated docs index (${path.relative(ROOT, file)}).`);
}

if (import.meta.main) {
  main();
}
