#!/usr/bin/env bun
/**
 * Generates the `@checkstack/sdk` package from the platform's source of
 * truth: the per-plugin oRPC contracts (`*Api` `ClientDefinition`s exported
 * from each `@checkstack/<plugin>-common`) and the script-authoring helper
 * type builders (`scriptContext.ts` `_internals`).
 *
 * Emits (all committed):
 *   core/sdk/package.json            - name + version STAMPED from @checkstack/release
 *   core/sdk/src/contracts.ts        - re-export of every *Api ClientDefinition
 *   core/sdk/src/client.ts           - CheckstackClient type + createCheckstackClient
 *   core/sdk/src/healthcheck.ts      - defineHealthCheck identity runtime + types
 *   core/sdk/src/integration.ts      - defineIntegration identity runtime + types
 *   core/sdk/src/index.ts            - root re-export surface
 *   core/sdk/src/version.ts          - stamped release version (frontend-safe)
 *   core/sdk/src/editor-bundle.ts    - runtime editor bundle (backend-only)
 *   core/sdk/generated/index.d.ts        - root subpath `types` target
 *   core/sdk/generated/healthcheck.d.ts  - ./healthcheck subpath `types` target
 *   core/sdk/generated/integration.d.ts  - ./integration subpath `types` target
 *   core/sdk/generated/editor-bundle.d.ts - combined ambient .d.ts (editor only)
 *
 * Modes:
 *   - default: write the generated files to disk.
 *   - --check: regenerate to in-memory buffers and diff against the committed
 *     files; exit 1 on drift. Run in CI so a contract change without a
 *     regenerated SDK fails (mirrors `typecheck:references:check`).
 *
 * Idempotent: a fresh run on unchanged inputs produces byte-identical output.
 *
 * Single source of truth: the helper interface bodies AND the editor ambient
 * bundle are both derived from the SAME `scriptContext.ts` `_internals`
 * builders, so the runtime `src/*.ts`, the per-subpath `generated/*.d.ts`, and
 * the editor bundle can never drift from the in-editor declarations.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { _internals } from "../core/ui/src/components/CodeEditor/scriptContext.ts";

const ROOT = process.cwd();
const SDK_DIR = path.join(ROOT, "core", "sdk");
const SRC_DIR = path.join(SDK_DIR, "src");
const GENERATED_DIR = path.join(SDK_DIR, "generated");
const RELEASE_PKG = path.join(ROOT, "core", "release", "package.json");
const CHANGESET_DIR = path.join(ROOT, ".changeset");

/** The published package name. A changeset must never reference it (§7.3). */
const SDK_PACKAGE_NAME = "@checkstack/sdk";

const CHECK_ONLY = process.argv.includes("--check");

const GENERATED_BANNER =
  "// AUTO-GENERATED by scripts/generate-sdk.ts - DO NOT EDIT BY HAND.\n" +
  "// Run `bun run generate:sdk` after changing a *-common contract or the\n" +
  "// script-context helper builders.\n";

/**
 * Authoritative plugin manifest. Each entry maps a plugin to:
 *  - `pluginId`: the runtime key the root oRPC router nests under
 *    (`api-router.ts` `rootRpcRouter[pluginId]`), which is the key on the
 *    generated `CheckstackClient`.
 *  - `pkg`: the `-common` package the `*Api` `ClientDefinition` is exported
 *    from.
 *  - `apiExport`: the exported `ClientDefinition` symbol name.
 *
 * Kept explicit (not auto-discovered) so the generated surface is reviewable
 * in a diff and a new plugin is a deliberate one-line addition.
 */
interface PluginEntry {
  pluginId: string;
  pkg: string;
  apiExport: string;
}

export const PLUGINS: readonly PluginEntry[] = [
  { pluginId: "announcement", pkg: "@checkstack/announcement-common", apiExport: "AnnouncementApi" },
  { pluginId: "anomaly", pkg: "@checkstack/anomaly-common", apiExport: "AnomalyApi" },
  { pluginId: "auth", pkg: "@checkstack/auth-common", apiExport: "AuthApi" },
  { pluginId: "automation", pkg: "@checkstack/automation-common", apiExport: "AutomationApi" },
  { pluginId: "cache", pkg: "@checkstack/cache-common", apiExport: "CacheApi" },
  { pluginId: "catalog", pkg: "@checkstack/catalog-common", apiExport: "CatalogApi" },
  { pluginId: "command", pkg: "@checkstack/command-common", apiExport: "CommandApi" },
  { pluginId: "dependency", pkg: "@checkstack/dependency-common", apiExport: "DependencyApi" },
  { pluginId: "gitops", pkg: "@checkstack/gitops-common", apiExport: "GitOpsApi" },
  { pluginId: "healthcheck", pkg: "@checkstack/healthcheck-common", apiExport: "HealthCheckApi" },
  { pluginId: "incident", pkg: "@checkstack/incident-common", apiExport: "IncidentApi" },
  { pluginId: "integration", pkg: "@checkstack/integration-common", apiExport: "IntegrationApi" },
  { pluginId: "maintenance", pkg: "@checkstack/maintenance-common", apiExport: "MaintenanceApi" },
  { pluginId: "notification", pkg: "@checkstack/notification-common", apiExport: "NotificationApi" },
  { pluginId: "pluginmanager", pkg: "@checkstack/pluginmanager-common", apiExport: "PluginManagerApi" },
  { pluginId: "queue", pkg: "@checkstack/queue-common", apiExport: "QueueApi" },
  { pluginId: "satellite", pkg: "@checkstack/satellite-common", apiExport: "SatelliteApi" },
  { pluginId: "script-packages", pkg: "@checkstack/script-packages-common", apiExport: "ScriptPackagesApi" },
  { pluginId: "secrets", pkg: "@checkstack/secrets-common", apiExport: "SecretsApi" },
  { pluginId: "slo", pkg: "@checkstack/slo-common", apiExport: "SloApi" },
  { pluginId: "theme", pkg: "@checkstack/theme-common", apiExport: "ThemeApi" },
  { pluginId: "tips", pkg: "@checkstack/tips-common", apiExport: "TipsApi" },
] as const;

const GENERIC_CONFIG = "Record<string, unknown>";

/**
 * A TS object-property key must be quoted when it is not a valid identifier
 * (e.g. `script-packages` contains a hyphen).
 */
function propertyKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

/**
 * Extracts a top-level `interface <name> { ... }` block (with its leading
 * JSDoc comment, if any) from the text produced by a `_internals` helper
 * builder. We reuse the SAME source text the editor uses, so the SDK's
 * runtime types can never drift from the in-editor declarations.
 */
function extractInterface({
  source,
  name,
}: {
  source: string;
  name: string;
}): string {
  const marker = `interface ${name} {`;
  const start = source.indexOf(marker);
  if (start === -1) {
    throw new Error(`Could not find "interface ${name}" in helper source.`);
  }

  // Walk back over an immediately-preceding JSDoc block (only whitespace may
  // separate it from the `interface` keyword). Find the LAST `*/` before the
  // interface and the `/**` that opens that same block - NOT an earlier one,
  // so we don't swallow a previous interface's text.
  let blockStart = start;
  const before = source.slice(0, start);
  const trimmedLen = before.replace(/\s+$/, "").length;
  if (before.slice(trimmedLen - 2, trimmedLen) === "*/") {
    const openIdx = before.lastIndexOf("/**", trimmedLen - 2);
    if (openIdx !== -1) {
      blockStart = openIdx;
    }
  }

  // Brace-match from the opening `{` of the interface to its close.
  const braceOpen = source.indexOf("{", start);
  let depth = 0;
  let end = -1;
  for (let i = braceOpen; i < source.length; i++) {
    const ch = source[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) {
    throw new Error(`Unbalanced braces extracting "interface ${name}".`);
  }

  return source.slice(blockStart, end).trim();
}

interface HelperShape {
  /** Subpath segment, e.g. "healthcheck". */
  subpath: string;
  /** The helper function name, e.g. "defineHealthCheck". */
  fnName: string;
  /** `interface ...Result { ... }` text. */
  resultInterface: string;
  /** `interface ...Context { ... }` text. */
  contextInterface: string;
  /** Result type name. */
  resultName: string;
  /** Context type name. */
  contextName: string;
  /** The generic `defineX<...>(value: T): T` declaration body (no `declare`). */
  defineSignature: string;
}

/**
 * Builds the structural pieces for one helper subpath by reusing the editor's
 * own `_internals` builder text (single source of truth).
 */
function buildHelperShape({
  subpath,
  fnName,
  resultName,
  contextName,
  builderText,
}: {
  subpath: string;
  fnName: string;
  resultName: string;
  contextName: string;
  builderText: string;
}): HelperShape {
  const resultInterface = extractInterface({ source: builderText, name: resultName });
  const contextInterface = extractInterface({ source: builderText, name: contextName });

  // Extract the generic `declare function <fn><...>(value: T): T;` block and
  // strip the `declare ` so it can back both a runtime function (in src) and a
  // declaration (in generated .d.ts).
  const declMarker = `declare function ${fnName}`;
  const declStart = builderText.indexOf(declMarker);
  if (declStart === -1) {
    throw new Error(`Could not find "declare function ${fnName}".`);
  }
  const declEnd = builderText.indexOf(";", declStart);
  if (declEnd === -1) {
    throw new Error(`Unterminated "declare function ${fnName}".`);
  }
  // Strip the leading `declare function ` so `defineSignature` is just
  // `<fn><...>(value: T): T;` - callers re-add the appropriate prefix
  // (`export function`, `export declare function`, or `declare function`).
  const defineSignature = builderText
    .slice(declStart, declEnd + 1)
    .replace(/^declare\s+function\s+/, "")
    .trim();

  return {
    subpath,
    fnName,
    resultInterface,
    contextInterface,
    resultName,
    contextName,
    defineSignature,
  };
}

/**
 * Renders the runtime `src/<subpath>.ts` for a helper: the interfaces plus the
 * identity-function implementation (behaviorally identical to the in-app
 * `esm-script-runner` rewrite, see plan §3.7/§6.3).
 */
function renderHelperSrc(shape: HelperShape): string {
  const { fnName, resultName, contextName, resultInterface, contextInterface } =
    shape;
  // `defineSignature` is `defineX<T extends ...>(value: T): T;` - turn it into a
  // function definition that returns its argument unchanged.
  const fnDef = shape.defineSignature.replace(/;$/, " {\n  return value;\n}");
  return (
    GENERATED_BANNER +
    "\n" +
    resultInterface +
    "\n\n" +
    contextInterface +
    "\n\n" +
    // Re-export the context + result interfaces as types so the package barrel
    // (`export * from "./<subpath>.ts"`) surfaces them. Without this, only the
    // `defineX` function is re-exported and `HealthCheckScriptContext` /
    // `IntegrationScriptContext` are unreachable to consumers (plan Phase-1
    // MINOR: `export type` the helper context interfaces from the runtime barrel).
    `export type { ${resultName}, ${contextName} };\n\n` +
    "/**\n" +
    ` * Identity helper for ${fnName} scripts. The value is returned unchanged at\n` +
    " * runtime - the function only narrows what `export default` may be so\n" +
    " * mistakes are caught before the script runs. Matches the in-app runner's\n" +
    " * injected helper body exactly (esm-script-runner identity rewrite).\n" +
    " */\n" +
    "export function " +
    fnDef +
    "\n"
  );
}

/**
 * Renders the per-subpath `generated/<subpath>.d.ts` - the `exports`-`types`
 * target external `npm install` resolves under node16/nodenext/bundler. Its
 * top-level exports ARE exactly that subpath's surface.
 */
function renderHelperDts(shape: HelperShape): string {
  const { resultName, contextName, resultInterface, contextInterface, defineSignature } =
    shape;
  return (
    GENERATED_BANNER +
    "\n" +
    resultInterface +
    "\n\n" +
    contextInterface +
    "\n\n" +
    "export declare function " +
    defineSignature +
    "\n\n" +
    `export type { ${resultName}, ${contextName} };\n`
  );
}

/** Re-indents a block of text by `spaces` (used to nest interfaces inside a
 * `declare module { ... }` block). Blank lines stay blank. */
function indentBlock(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}

/**
 * Renders the SELF-CONTAINED ambient `declare module "@checkstack/sdk/<subpath>"`
 * block for the editor bundle. The interfaces and the `defineX` function live
 * INSIDE the module block (exported from it) rather than as top-level globals.
 *
 * Why module-internal and NOT top-level globals: the editor mounts this bundle
 * ALONGSIDE the per-editor `scriptContext.ts` declarations, which ALREADY
 * declare the global `defineHealthCheck` / `defineIntegration` + the
 * schema-narrowed `HealthCheckScriptContext` / `IntegrationScriptContext`
 * (their raison d'être, plan §6.2). Re-declaring those as top-level globals
 * here too would produce duplicate-identifier / duplicate-implementation errors
 * in the shared TS language service. Keeping them module-scoped means
 * `import { defineHealthCheck } from "@checkstack/sdk/healthcheck"` resolves
 * cleanly while no-import autocomplete still works via scriptContext's globals.
 */
function renderHelperAmbient(shape: HelperShape): string {
  const { subpath, resultInterface, contextInterface, defineSignature } = shape;
  return (
    `declare module "@checkstack/sdk/${subpath}" {\n` +
    indentBlock(resultInterface, 2) +
    "\n\n" +
    indentBlock(contextInterface, 2) +
    "\n\n" +
    indentBlock("export function " + defineSignature, 2) +
    "\n" +
    `  export type { ${shape.resultName}, ${shape.contextName} };\n` +
    "}\n"
  );
}

/**
 * Renders the root `declare module "@checkstack/sdk"` block for the editor
 * bundle. It re-exports the helper symbols from the subpath modules (so
 * `import { defineHealthCheck } from "@checkstack/sdk"` also resolves in the
 * editor) and declares the typed-client factory surface. Self-contained: no
 * top-level globals, so it cannot collide with scriptContext (see
 * `renderHelperAmbient`).
 */
function renderRootAmbient(hc: HelperShape, intg: HelperShape): string {
  return (
    'declare module "@checkstack/sdk" {\n' +
    `  export { defineHealthCheck } from "@checkstack/sdk/healthcheck";\n` +
    `  export type { ${hc.resultName}, ${hc.contextName} } from "@checkstack/sdk/healthcheck";\n` +
    `  export { defineIntegration } from "@checkstack/sdk/integration";\n` +
    `  export type { ${intg.resultName}, ${intg.contextName} } from "@checkstack/sdk/integration";\n` +
    "  export interface CreateCheckstackClientOptions {\n" +
    "    baseUrl: string;\n" +
    "    headers?: Record<string, string>;\n" +
    "  }\n" +
    "  /** The fully-typed Checkstack API client (one entry per plugin id). */\n" +
    "  export type CheckstackClient = Record<string, unknown>;\n" +
    "  /** Build a typed Checkstack client over the REST/OpenAPI surface. */\n" +
    "  export function createCheckstackClient(\n" +
    "    options: CreateCheckstackClientOptions,\n" +
    "  ): CheckstackClient;\n" +
    "}\n"
  );
}

function renderContracts(): string {
  // All *Api symbols come from distinct packages; emit one re-export per package.
  const importLines = PLUGINS.map(
    (p) => `export { ${p.apiExport} } from "${p.pkg}";`,
  ).join("\n");
  return (
    GENERATED_BANNER +
    "\n" +
    "/**\n" +
    " * Re-export of every per-plugin oRPC contract `ClientDefinition`. Each is\n" +
    " * the source-of-truth API surface the running backend serves at\n" +
    " * `/rest/:pluginId/*`.\n" +
    " */\n" +
    importLines +
    "\n"
  );
}

function renderClient(): string {
  const valueImports = PLUGINS.map(
    (p) => `import { ${p.apiExport} } from "${p.pkg}";`,
  ).join("\n");

  const clientFields = PLUGINS.map(
    (p) => `  ${propertyKey(p.pluginId)}: InferClient<typeof ${p.apiExport}>;`,
  ).join("\n");

  // The OpenAPILink needs the SAME nested contract router the backend serves
  // (`rootRpcRouter[pluginId]`, prefix `/rest`) so it can map procedure calls
  // to REST routes. Assemble it from each ClientDefinition's `.contract`.
  const contractFields = PLUGINS.map(
    (p) => `  ${propertyKey(p.pluginId)}: ${p.apiExport}.contract,`,
  ).join("\n");

  return (
    GENERATED_BANNER +
    "\n" +
    'import { createORPCClient } from "@orpc/client";\n' +
    'import { OpenAPILink } from "@orpc/openapi-client/fetch";\n' +
    'import type { InferClient } from "@checkstack/common";\n' +
    valueImports +
    "\n\n" +
    "/**\n" +
    " * The fully-typed Checkstack API client. One entry per plugin id, mirroring\n" +
    " * the backend's root oRPC router nesting (`rootRpcRouter[pluginId]`). Each\n" +
    " * value is the contract's inferred client (`InferClient`).\n" +
    " */\n" +
    "export interface CheckstackClient {\n" +
    clientFields +
    "\n}\n\n" +
    "/** Options for {@link createCheckstackClient}. */\n" +
    "export interface CreateCheckstackClientOptions {\n" +
    "  /** Base URL of the Checkstack REST surface, e.g. `https://host/rest`. */\n" +
    "  baseUrl: string;\n" +
    "  /** Extra request headers, e.g. API-key / bearer auth. */\n" +
    "  headers?: Record<string, string>;\n" +
    "}\n\n" +
    "/**\n" +
    " * The nested contract router mirroring the backend's `/rest/:pluginId/*`\n" +
    " * surface. Passed to {@link OpenAPILink} so calls map to REST routes.\n" +
    " */\n" +
    "const checkstackContract = {\n" +
    contractFields +
    "\n};\n\n" +
    "/**\n" +
    " * Build a typed Checkstack client over the REST/OpenAPI surface\n" +
    " * (`/rest/:pluginId/*`). Each plugin is reachable under its plugin id.\n" +
    " */\n" +
    "export function createCheckstackClient({\n" +
    "  baseUrl,\n" +
    "  headers,\n" +
    "}: CreateCheckstackClientOptions): CheckstackClient {\n" +
    "  // Strip trailing slashes without a backtracking-prone regex\n" +
    "  // (`/\\/+$/` is O(n^2) on inputs like \"////...x\" - CodeQL js/polynomial-redos).\n" +
    "  let normalizedBase = baseUrl;\n" +
    "  while (normalizedBase.endsWith(\"/\")) normalizedBase = normalizedBase.slice(0, -1);\n" +
    "  const link = new OpenAPILink(checkstackContract, {\n" +
    "    url: normalizedBase,\n" +
    "    headers: () => headers ?? {},\n" +
    "  });\n" +
    "  // oRPC's `createORPCClient` constrains its type param to an index-signature\n" +
    "  // `NestedClient`, which a fixed-key interface like `CheckstackClient` cannot\n" +
    "  // satisfy structurally. The runtime client IS the CheckstackClient shape\n" +
    "  // (one entry per plugin contract), so cast through the oRPC-inferred client.\n" +
    "  // Mirrors core/frontend/src/apis/rpc-api.ts.\n" +
    "  return createORPCClient(link) as unknown as CheckstackClient;\n" +
    "}\n"
  );
}

function renderIndexSrc(): string {
  return (
    GENERATED_BANNER +
    "\n" +
    'export * from "./contracts.ts";\n' +
    'export * from "./client.ts";\n' +
    'export * from "./healthcheck.ts";\n' +
    'export * from "./integration.ts";\n' +
    'export type { InferClient, ClientDefinition } from "@checkstack/common";\n'
  );
}

function renderIndexDts(hc: HelperShape, intg: HelperShape): string {
  const clientFields = PLUGINS.map(
    (p) => `  ${propertyKey(p.pluginId)}: InferClient<typeof ${p.apiExport}>;`,
  ).join("\n");
  const typeImports = PLUGINS.map(
    (p) => `import type { ${p.apiExport} } from "${p.pkg}";`,
  ).join("\n");
  // Value re-export of every contract ClientDefinition, one per package.
  const apiReexports = PLUGINS.map(
    (p) => `export { ${p.apiExport} } from "${p.pkg}";`,
  ).join("\n");

  return (
    GENERATED_BANNER +
    "\n" +
    'import type { InferClient } from "@checkstack/common";\n' +
    typeImports +
    "\n\n" +
    "export interface CheckstackClient {\n" +
    clientFields +
    "\n}\n\n" +
    "export interface CreateCheckstackClientOptions {\n" +
    "  baseUrl: string;\n" +
    "  headers?: Record<string, string>;\n" +
    "}\n\n" +
    "export declare function createCheckstackClient(\n" +
    "  options: CreateCheckstackClientOptions,\n" +
    "): CheckstackClient;\n\n" +
    apiReexports +
    "\n\n" +
    "// Script-authoring helpers (also available under the per-subpath exports).\n" +
    hc.resultInterface +
    "\n\n" +
    hc.contextInterface +
    "\n\n" +
    intg.resultInterface +
    "\n\n" +
    intg.contextInterface +
    "\n\n" +
    "export declare function " +
    hc.defineSignature +
    "\n" +
    "export declare function " +
    intg.defineSignature +
    "\n" +
    `export type {\n  ${hc.resultName},\n  ${hc.contextName},\n  ${intg.resultName},\n  ${intg.contextName},\n};\n\n` +
    'export type { InferClient, ClientDefinition } from "@checkstack/common";\n'
  );
}

function renderEditorBundle(hc: HelperShape, intg: HelperShape): string {
  return (
    GENERATED_BANNER +
    "\n" +
    "// Combined ambient declarations served ONLY by the version-keyed editor\n" +
    "// route and mounted into Monaco. NOT the `exports`-resolved declarations\n" +
    "// (those are the per-subpath generated/*.d.ts). Declares the subpath module\n" +
    "// names only - bare names are intentionally absent so an old import errors.\n" +
    "//\n" +
    "// Every declaration is module-scoped (no top-level globals): the editor\n" +
    "// mounts this bundle alongside scriptContext.ts, which owns the global\n" +
    "// `defineHealthCheck` / `defineIntegration` + schema-narrowed context types\n" +
    "// (plan §6.2). Top-level globals here would duplicate those and error.\n" +
    "\n" +
    renderHelperAmbient(hc) +
    "\n" +
    renderHelperAmbient(intg) +
    "\n" +
    renderRootAmbient(hc, intg)
  );
}

/**
 * Renders the runtime `src/editor-bundle.ts` module. It exports the editor
 * bundle `.d.ts` text AND the stamped release version as plain string
 * constants so the backend SDK-types route can serve them WITHOUT a filesystem
 * read (deploy-safe: it's real bundled TS, not a runtime `fs` lookup of a
 * `.d.ts` under `generated/`). Served by `script-packages-backend`'s
 * version-keyed route and mounted into Monaco (plan §6.1).
 *
 * `JSON.stringify` escapes the multi-line declaration text into a safe
 * double-quoted string literal (newlines become `\n`, backticks/`${` are
 * inert), so the emitted module is always valid TS regardless of the bundle's
 * content.
 */
function renderEditorBundleModule({ bundle }: { bundle: string }): string {
  return (
    GENERATED_BANNER +
    "\n" +
    "// Runtime-importable copy of the editor bundle, served by the\n" +
    "// @checkstack/sdk editor-types backend route (plan §6.1). Imported by\n" +
    "// the BACKEND only - it embeds the full bundle text, which the frontend\n" +
    "// must NOT bundle (it fetches the bundle live; see ./version.ts).\n" +
    "\n" +
    "/** The combined ambient `.d.ts` the in-app editor mounts into Monaco. */\n" +
    "export const SDK_EDITOR_BUNDLE_DTS = " +
    JSON.stringify(bundle) +
    ";\n\n" +
    'export { SDK_RELEASE_VERSION } from "./version.ts";\n'
  );
}

/** Declaration companion for `src/editor-bundle.ts` (the `types` condition of
 * the `./editor-bundle` subpath). Stable surface (no embedded content), so it
 * stays byte-identical across releases. */
function renderEditorBundleModuleDts(): string {
  return (
    GENERATED_BANNER +
    "\n" +
    "/** The combined ambient `.d.ts` the in-app editor mounts into Monaco. */\n" +
    "export declare const SDK_EDITOR_BUNDLE_DTS: string;\n" +
    'export { SDK_RELEASE_VERSION } from "./version.d.ts";\n'
  );
}

/** Declaration companion for `src/version.ts` (the `types` condition of the
 * `./version` subpath). Stable surface. */
function renderVersionModuleDts(): string {
  return (
    GENERATED_BANNER +
    "\n" +
    "/** The platform release version this SDK was stamped to. */\n" +
    "export declare const SDK_RELEASE_VERSION: string;\n"
  );
}

/**
 * Renders the tiny `src/version.ts` exporting ONLY the stamped release version.
 * Safe for the FRONTEND to import (the version-keyed editor-route cache key)
 * without pulling the heavy bundle text or the typed client into the frontend
 * bundle (plan §6.1/§6.2).
 */
function renderVersionModule({ version }: { version: string }): string {
  return (
    GENERATED_BANNER +
    "\n" +
    "/** The platform release version this SDK was stamped to. */\n" +
    "export const SDK_RELEASE_VERSION = " +
    JSON.stringify(version) +
    ";\n"
  );
}

export interface EmitFile {
  /** absolute path */
  file: string;
  content: string;
}

export function readReleaseVersion(): string {
  const pkg = JSON.parse(readFileSync(RELEASE_PKG, "utf8")) as {
    version?: string;
  };
  if (!pkg.version) {
    throw new Error(`@checkstack/release package.json has no version.`);
  }
  return pkg.version;
}

/**
 * The committed package.json. Only `version` is stamped; everything else is
 * static and hand-maintained (deps, exports map, scripts). We re-serialize the
 * existing file with the stamped version so a `--check` run is deterministic.
 */
function renderPackageJson({ version }: { version: string }): string {
  const pkgPath = path.join(SDK_DIR, "package.json");
  const current = JSON.parse(readFileSync(pkgPath, "utf8")) as Record<
    string,
    unknown
  >;
  current.version = version;
  return JSON.stringify(current, undefined, 2) + "\n";
}

/**
 * Builds every committed SDK file in memory. Pure with respect to its inputs:
 * pass `version` to stamp a fixture release version in tests; otherwise the
 * real `@checkstack/release` version is read.
 */
export function buildEmitFiles({
  version: versionOverride,
}: { version?: string } = {}): EmitFile[] {
  const hcBuilder = _internals.buildHealthCheckTypes(GENERIC_CONFIG);
  const intgBuilder = _internals.buildIntegrationTypes(GENERIC_CONFIG);

  const hc = buildHelperShape({
    subpath: "healthcheck",
    fnName: "defineHealthCheck",
    resultName: "HealthCheckScriptResult",
    contextName: "HealthCheckScriptContext",
    builderText: hcBuilder,
  });
  const intg = buildHelperShape({
    subpath: "integration",
    fnName: "defineIntegration",
    resultName: "IntegrationScriptResult",
    contextName: "IntegrationScriptContext",
    builderText: intgBuilder,
  });

  const version = versionOverride ?? readReleaseVersion();
  const editorBundle = renderEditorBundle(hc, intg);

  return [
    { file: path.join(SDK_DIR, "package.json"), content: renderPackageJson({ version }) },
    { file: path.join(SRC_DIR, "contracts.ts"), content: renderContracts() },
    { file: path.join(SRC_DIR, "client.ts"), content: renderClient() },
    { file: path.join(SRC_DIR, "healthcheck.ts"), content: renderHelperSrc(hc) },
    { file: path.join(SRC_DIR, "integration.ts"), content: renderHelperSrc(intg) },
    { file: path.join(SRC_DIR, "index.ts"), content: renderIndexSrc() },
    {
      file: path.join(SRC_DIR, "version.ts"),
      content: renderVersionModule({ version }),
    },
    {
      file: path.join(SRC_DIR, "editor-bundle.ts"),
      content: renderEditorBundleModule({ bundle: editorBundle }),
    },
    { file: path.join(GENERATED_DIR, "index.d.ts"), content: renderIndexDts(hc, intg) },
    { file: path.join(GENERATED_DIR, "healthcheck.d.ts"), content: renderHelperDts(hc) },
    { file: path.join(GENERATED_DIR, "integration.d.ts"), content: renderHelperDts(intg) },
    { file: path.join(GENERATED_DIR, "editor-bundle.d.ts"), content: editorBundle },
    {
      file: path.join(GENERATED_DIR, "version.d.ts"),
      content: renderVersionModuleDts(),
    },
    {
      file: path.join(GENERATED_DIR, "editor-bundle-module.d.ts"),
      content: renderEditorBundleModuleDts(),
    },
  ];
}

/**
 * The generated DECLARATION-SURFACE files - the `.d.ts` that external
 * `npm install` resolves through the `exports` map plus the editor bundle.
 * These describe the SDK's public API surface; a change to any of them means
 * the published SDK surface changed and so the package must republish (§7.1.1).
 *
 * `package.json` (only the stamped `version` differs between releases) and the
 * runtime `src/*.ts` are deliberately excluded: the §7.1.1 guard is about the
 * SDK's *consumer-facing surface*, not the version stamp (which only advances
 * when a changeset is consumed - the very thing the guard enforces).
 */
const SURFACE_FILES = [
  "generated/index.d.ts",
  "generated/healthcheck.d.ts",
  "generated/integration.d.ts",
  "generated/editor-bundle.d.ts",
] as const;

/**
 * Lists the pending changeset markdown files (everything under `.changeset`
 * except `README.md` and non-`.md` config files). Mirrors `inject-release.ts`.
 */
export function listPendingChangesets(
  changesetDir: string = CHANGESET_DIR,
): string[] {
  if (!existsSync(changesetDir)) return [];
  return readdirSync(changesetDir, { withFileTypes: true })
    .filter(
      (e) => e.isFile() && e.name.endsWith(".md") && e.name !== "README.md",
    )
    .map((e) => e.name);
}

/**
 * Returns the changeset files (if any) whose frontmatter names
 * `@checkstack/sdk`. The SDK version is stamped from `@checkstack/release`, so
 * a hand-written changeset bumping it would fight the stamp (§7.3).
 */
export function changesetsNamingSdk(
  changesetDir: string = CHANGESET_DIR,
): string[] {
  const offenders: string[] = [];
  // Matches a frontmatter line like: "@checkstack/sdk": minor
  const sdkLine = /^["']?@checkstack\/sdk["']?\s*:\s*(major|minor|patch)\s*$/m;
  for (const file of listPendingChangesets(changesetDir)) {
    const content = readFileSync(path.join(changesetDir, file), "utf8");
    if (sdkLine.test(content)) offenders.push(file);
  }
  return offenders;
}

/**
 * Resolves the git ref to diff the SDK surface against for the §7.1.1 guard.
 * Prefers the changeset base branch (`origin/main`, then `main`), then the
 * parent commit. Returns `undefined` when none resolve (e.g. a shallow CI
 * checkout or a fresh repo) so the guard degrades gracefully - the primary
 * drift check still runs.
 */
export function resolveSurfaceBaseRef({
  cwd = ROOT,
  candidates = ["origin/main", "main", "HEAD^"],
}: {
  cwd?: string;
  candidates?: string[];
} = {}): string | undefined {
  for (const ref of candidates) {
    const res = spawnSync("git", ["rev-parse", "--verify", "--quiet", ref], {
      cwd,
      encoding: "utf8",
    });
    if (res.status === 0) return ref;
  }
  return undefined;
}

/**
 * Reads a committed file at a git ref via `git show <ref>:<relpath>`. Returns
 * `undefined` when the file does not exist at that ref (e.g. the SDK was added
 * in this branch).
 */
function gitShow({
  ref,
  relPath,
  cwd = ROOT,
}: {
  ref: string;
  relPath: string;
  cwd?: string;
}): string | undefined {
  const res = spawnSync("git", ["show", `${ref}:${relPath}`], {
    cwd,
    encoding: "utf8",
  });
  if (res.status !== 0) return undefined;
  return res.stdout;
}

/**
 * Compares the freshly-generated SDK declaration surface against the version
 * committed at `baseRef`. Returns the relative paths whose surface changed.
 * A NEW surface file (absent at base) counts as a change.
 */
export function sdkSurfaceDriftFromBase({
  files,
  baseRef,
  cwd = ROOT,
}: {
  files: EmitFile[];
  baseRef: string;
  cwd?: string;
}): string[] {
  const drifted: string[] = [];
  for (const rel of SURFACE_FILES) {
    const abs = path.join(SDK_DIR, rel);
    const fresh = files.find((f) => f.file === abs)?.content;
    if (fresh === undefined) continue;
    const relFromRoot = path.relative(cwd, abs);
    const base = gitShow({ ref: baseRef, relPath: relFromRoot, cwd });
    if (base !== fresh) drifted.push(relFromRoot);
  }
  return drifted;
}

function main() {
  const files = buildEmitFiles();

  if (CHECK_ONLY) {
    // §7.3: a changeset must never name @checkstack/sdk (the version is
    // stamped from @checkstack/release, so a changeset bump would fight it).
    const sdkChangesets = changesetsNamingSdk();
    if (sdkChangesets.length > 0) {
      console.error(
        `❌ A pending changeset references ${SDK_PACKAGE_NAME}, but its version ` +
          "is stamped from @checkstack/release and MUST NOT appear in a " +
          "changeset (plan §7.3):",
      );
      for (const f of sdkChangesets) console.error(`   - .changeset/${f}`);
      console.error(
        "\nRemove @checkstack/sdk from the changeset frontmatter. Put the bump " +
          "on the underlying *-common / platform package instead.",
      );
      process.exit(1);
    }

    // Primary drift guard: the committed files must match a fresh generation.
    const drifted: string[] = [];
    for (const { file, content } of files) {
      const prev = existsSync(file) ? readFileSync(file, "utf8") : undefined;
      if (prev !== content) drifted.push(path.relative(ROOT, file));
    }
    if (drifted.length > 0) {
      console.error(
        `❌ ${drifted.length} @checkstack/sdk file(s) are out of sync with the ` +
          "contracts / helper builders:",
      );
      for (const f of drifted) console.error(`   - ${f}`);
      console.error(
        "\nRun `bun run generate:sdk` and commit the changes. A *-common contract " +
          "change MUST carry a changeset on the underlying package (plan §7.1.1).",
      );
      process.exit(1);
    }

    // §7.1.1: even with the committed files regenerated (no drift above), if
    // the SDK's published declaration surface changed relative to the base
    // branch AND there is NO pending changeset, the release version would not
    // advance, the stamp would not increment, and the SDK would silently fail
    // to republish - the exact gap this feature exists to close. Make it a
    // hard CI error.
    const baseRef = resolveSurfaceBaseRef();
    if (baseRef) {
      const surfaceDrift = sdkSurfaceDriftFromBase({ files, baseRef });
      const pending = listPendingChangesets();
      if (surfaceDrift.length > 0 && pending.length === 0) {
        console.error(
          `❌ The @checkstack/sdk published surface changed vs ${baseRef} but ` +
            "no changeset is pending:",
        );
        for (const f of surfaceDrift) console.error(`   - ${f}`);
        console.error(
          "\nA change to a *-common contract (or the script-context helper " +
            "builders) changes the generated SDK surface. It MUST carry a " +
            "changeset on the underlying package so @checkstack/release advances " +
            "and the stamped SDK version republishes (plan §7.1.1). Add a " +
            "changeset with `bun changeset`.",
        );
        process.exit(1);
      }
    } else {
      console.warn(
        "⚠ Could not resolve a git base ref; skipping the SDK-surface-drift " +
          "changeset guard (§7.1.1). The primary drift check still ran.",
      );
    }

    console.log("✓ @checkstack/sdk generated files are up to date.");
    return;
  }

  mkdirSync(SRC_DIR, { recursive: true });
  mkdirSync(GENERATED_DIR, { recursive: true });
  for (const { file, content } of files) {
    writeFileSync(file, content, "utf8");
  }
  console.log(`✓ Generated ${files.length} @checkstack/sdk file(s).`);
}

if (import.meta.main) {
  main();
}
