import type { CacheManager } from "@checkstack/cache-api";
import {
  createCachedScope,
  type CachedScope,
} from "@checkstack/cache-utils";
import type { Logger } from "@checkstack/backend-api";

/**
 * 15s. Each `engine.computeStatus` call runs a SLO calculation over a
 * rolling window so this cache is more about CPU than DB. Downtime events
 * generated by the SLO engine can change status outside any tRPC mutation,
 * so the TTL doubles as a freshness ceiling for that path.
 */
const SLO_TTL_MS = 15_000;

const LIST_KEY = "list:objectives";
const OBJECTIVE_PREFIX = "objective:";
const SYSTEM_PREFIX = "system:";

const objectiveKey = (id: string): string => `${OBJECTIVE_PREFIX}${id}`;
const systemKey = (systemId: string): string => `${SYSTEM_PREFIX}${systemId}`;

export interface SloCache {
  wrapList: <T>(loader: () => Promise<T>) => Promise<T>;
  wrapObjective: <T>(id: string, loader: () => Promise<T>) => Promise<T>;
  wrapSystem: <T>(
    systemId: string,
    loader: () => Promise<T>,
  ) => Promise<T>;

  /**
   * Drop all cached entries affected by a mutation that touches one
   * objective on one system. Always awaits before signal broadcast.
   */
  invalidateForMutation: (props: {
    objectiveId: string;
    systemId: string;
  }) => Promise<void>;

  scope: CachedScope;
}

export function createSloCache({
  cacheManager,
  logger,
}: {
  cacheManager: CacheManager;
  logger: Logger;
}): SloCache {
  const scope = createCachedScope({
    cacheManager,
    pluginId: "slo",
    defaultTtlMs: SLO_TTL_MS,
    onError: (op: string, error: unknown) => {
      logger.warn(`slo cache ${op} failed: ${String(error)}`);
    },
  });

  return {
    wrapList: (loader) => scope.wrap(LIST_KEY, loader),
    wrapObjective: (id, loader) => scope.wrap(objectiveKey(id), loader),
    wrapSystem: (systemId, loader) => scope.wrap(systemKey(systemId), loader),

    invalidateForMutation: async ({ objectiveId, systemId }) => {
      await Promise.all([
        scope.invalidate(LIST_KEY),
        scope.invalidate(objectiveKey(objectiveId)),
        scope.invalidate(systemKey(systemId)),
      ]);
    },

    scope,
  };
}
