// AUTO-GENERATED by scripts/generate-sdk.ts - DO NOT EDIT BY HAND.
// Run `bun run generate:sdk` after changing a *-common contract or the
// script-context helper builders.

import { createORPCClient } from "@orpc/client";
import { OpenAPILink } from "@orpc/openapi-client/fetch";
import type { InferClient } from "@checkstack/common";
import { AnnouncementApi } from "@checkstack/announcement-common";
import { AnomalyApi } from "@checkstack/anomaly-common";
import { AuthApi } from "@checkstack/auth-common";
import { AutomationApi } from "@checkstack/automation-common";
import { CacheApi } from "@checkstack/cache-common";
import { CatalogApi } from "@checkstack/catalog-common";
import { CommandApi } from "@checkstack/command-common";
import { DependencyApi } from "@checkstack/dependency-common";
import { GitOpsApi } from "@checkstack/gitops-common";
import { HealthCheckApi } from "@checkstack/healthcheck-common";
import { IncidentApi } from "@checkstack/incident-common";
import { IntegrationApi } from "@checkstack/integration-common";
import { MaintenanceApi } from "@checkstack/maintenance-common";
import { NotificationApi } from "@checkstack/notification-common";
import { PluginManagerApi } from "@checkstack/pluginmanager-common";
import { QueueApi } from "@checkstack/queue-common";
import { SatelliteApi } from "@checkstack/satellite-common";
import { ScriptPackagesApi } from "@checkstack/script-packages-common";
import { SecretsApi } from "@checkstack/secrets-common";
import { SloApi } from "@checkstack/slo-common";
import { ThemeApi } from "@checkstack/theme-common";
import { TipsApi } from "@checkstack/tips-common";

/**
 * The fully-typed Checkstack API client. One entry per plugin id, mirroring
 * the backend's root oRPC router nesting (`rootRpcRouter[pluginId]`). Each
 * value is the contract's inferred client (`InferClient`).
 */
export interface CheckstackClient {
  announcement: InferClient<typeof AnnouncementApi>;
  anomaly: InferClient<typeof AnomalyApi>;
  auth: InferClient<typeof AuthApi>;
  automation: InferClient<typeof AutomationApi>;
  cache: InferClient<typeof CacheApi>;
  catalog: InferClient<typeof CatalogApi>;
  command: InferClient<typeof CommandApi>;
  dependency: InferClient<typeof DependencyApi>;
  gitops: InferClient<typeof GitOpsApi>;
  healthcheck: InferClient<typeof HealthCheckApi>;
  incident: InferClient<typeof IncidentApi>;
  integration: InferClient<typeof IntegrationApi>;
  maintenance: InferClient<typeof MaintenanceApi>;
  notification: InferClient<typeof NotificationApi>;
  pluginmanager: InferClient<typeof PluginManagerApi>;
  queue: InferClient<typeof QueueApi>;
  satellite: InferClient<typeof SatelliteApi>;
  "script-packages": InferClient<typeof ScriptPackagesApi>;
  secrets: InferClient<typeof SecretsApi>;
  slo: InferClient<typeof SloApi>;
  theme: InferClient<typeof ThemeApi>;
  tips: InferClient<typeof TipsApi>;
}

/** Options for {@link createCheckstackClient}. */
export interface CreateCheckstackClientOptions {
  /** Base URL of the Checkstack REST surface, e.g. `https://host/rest`. */
  baseUrl: string;
  /** Extra request headers, e.g. API-key / bearer auth. */
  headers?: Record<string, string>;
}

/**
 * The nested contract router mirroring the backend's `/rest/:pluginId/*`
 * surface. Passed to {@link OpenAPILink} so calls map to REST routes.
 */
const checkstackContract = {
  announcement: AnnouncementApi.contract,
  anomaly: AnomalyApi.contract,
  auth: AuthApi.contract,
  automation: AutomationApi.contract,
  cache: CacheApi.contract,
  catalog: CatalogApi.contract,
  command: CommandApi.contract,
  dependency: DependencyApi.contract,
  gitops: GitOpsApi.contract,
  healthcheck: HealthCheckApi.contract,
  incident: IncidentApi.contract,
  integration: IntegrationApi.contract,
  maintenance: MaintenanceApi.contract,
  notification: NotificationApi.contract,
  pluginmanager: PluginManagerApi.contract,
  queue: QueueApi.contract,
  satellite: SatelliteApi.contract,
  "script-packages": ScriptPackagesApi.contract,
  secrets: SecretsApi.contract,
  slo: SloApi.contract,
  theme: ThemeApi.contract,
  tips: TipsApi.contract,
};

/**
 * Build a typed Checkstack client over the REST/OpenAPI surface
 * (`/rest/:pluginId/*`). Each plugin is reachable under its plugin id.
 */
export function createCheckstackClient({
  baseUrl,
  headers,
}: CreateCheckstackClientOptions): CheckstackClient {
  // Strip trailing slashes without a backtracking-prone regex
  // (`/\/+$/` is O(n^2) on inputs like "////...x" - CodeQL js/polynomial-redos).
  let normalizedBase = baseUrl;
  while (normalizedBase.endsWith("/")) normalizedBase = normalizedBase.slice(0, -1);
  const link = new OpenAPILink(checkstackContract, {
    url: normalizedBase,
    headers: () => headers ?? {},
  });
  // oRPC's `createORPCClient` constrains its type param to an index-signature
  // `NestedClient`, which a fixed-key interface like `CheckstackClient` cannot
  // satisfy structurally. The runtime client IS the CheckstackClient shape
  // (one entry per plugin contract), so cast through the oRPC-inferred client.
  // Mirrors core/frontend/src/apis/rpc-api.ts.
  return createORPCClient(link) as unknown as CheckstackClient;
}
