// AUTO-GENERATED by scripts/generate-sdk.ts - DO NOT EDIT BY HAND.
// Run `bun run generate:sdk` after changing a *-common contract or the
// script-context helper builders.

/**
 * Re-export of every per-plugin oRPC contract `ClientDefinition`. Each is
 * the source-of-truth API surface the running backend serves at
 * `/rest/:pluginId/*`.
 */
export { AnnouncementApi } from "@checkstack/announcement-common";
export { AnomalyApi } from "@checkstack/anomaly-common";
export { AuthApi } from "@checkstack/auth-common";
export { AutomationApi } from "@checkstack/automation-common";
export { CacheApi } from "@checkstack/cache-common";
export { CatalogApi } from "@checkstack/catalog-common";
export { CommandApi } from "@checkstack/command-common";
export { DependencyApi } from "@checkstack/dependency-common";
export { GitOpsApi } from "@checkstack/gitops-common";
export { HealthCheckApi } from "@checkstack/healthcheck-common";
export { IncidentApi } from "@checkstack/incident-common";
export { IntegrationApi } from "@checkstack/integration-common";
export { MaintenanceApi } from "@checkstack/maintenance-common";
export { NotificationApi } from "@checkstack/notification-common";
export { PluginManagerApi } from "@checkstack/pluginmanager-common";
export { QueueApi } from "@checkstack/queue-common";
export { SatelliteApi } from "@checkstack/satellite-common";
export { ScriptPackagesApi } from "@checkstack/script-packages-common";
export { SecretsApi } from "@checkstack/secrets-common";
export { SloApi } from "@checkstack/slo-common";
export { ThemeApi } from "@checkstack/theme-common";
export { TipsApi } from "@checkstack/tips-common";
