// AUTO-GENERATED by scripts/generate-sdk.ts - DO NOT EDIT BY HAND.
// Run `bun run generate:sdk` after changing a *-common contract or the
// script-context helper builders.

/** Result emitted by an inline health-check script. */
interface HealthCheckScriptResult {
  /** Whether the health check passed. */
  success: boolean;
  /** Optional status message — surfaces in the run detail. */
  message?: string;
  /** Optional numeric value — feeds the value chart + anomaly detection. */
  value?: number;
}

/**
 * Runtime context exposed to inline health-check scripts. `config` is
 * typed from the collector's own JSON Schema, so the fields you've
 * declared on the configuration are autocompletable inside the script.
 */
interface HealthCheckScriptContext {
  /** Strongly-typed collector configuration. */
  readonly config: Record<string, unknown>;
  /** Metadata about the health check this run is for. */
  readonly check: {
    /** The health check configuration id. */
    readonly id: string;
    /** The health check's display name (falls back to the id). */
    readonly name: string;
    /** The configured run interval, in seconds. */
    readonly intervalSeconds: number;
  };
  /** Metadata about the system this check runs for. */
  readonly system: {
    /** The system id. */
    readonly id: string;
    /** The system's display name (falls back to the id). */
    readonly name: string;
    /**
     * The system's free-form custom fields, with the original
     * (non-normalized) keys — so you read `metadata.baseUrl` directly.
     * Values are arbitrary JSON (metadata only, never secrets); narrow
     * each before use, e.g. `typeof metadata.baseUrl === "string"`.
     */
    readonly metadata: Record<string, unknown>;
  };
  /**
   * The environment this run resolved to, when the check fanned out into
   * one. `undefined` when the assignment opts out or the system has no
   * environments — always guard with `context.environment?.…`.
   */
  readonly environment?: {
    /** The environment id. */
    readonly id: string;
    /** The environment's display name (falls back to the id). */
    readonly name: string;
    /**
     * The environment's free-form custom metadata, with the original
     * (non-normalized) keys — so you read `fields.baseUrl` directly.
     * Values are arbitrary JSON (metadata only, never secrets); narrow
     * each before use, e.g. `typeof fields.baseUrl === "string"`.
     */
    readonly fields: Record<string, unknown>;
  };
}

export type { HealthCheckScriptResult, HealthCheckScriptContext };

/**
 * Identity helper for defineHealthCheck scripts. The value is returned unchanged at
 * runtime - the function only narrows what `export default` may be so
 * mistakes are caught before the script runs. Matches the in-app runner's
 * injected helper body exactly (esm-script-runner identity rewrite).
 */
export function defineHealthCheck<
  T extends
    | HealthCheckScriptResult
    | ((ctx: HealthCheckScriptContext) =>
        | HealthCheckScriptResult
        | Promise<HealthCheckScriptResult>),
>(value: T): T {
  return value;
}
