// AUTO-GENERATED by scripts/generate-sdk.ts - DO NOT EDIT BY HAND.
// Run `bun run generate:sdk` after changing a *-common contract or the
// script-context helper builders.

/** The platform release version this SDK was stamped to. */
export const SDK_RELEASE_VERSION = "0.107.0";
